name: PyPI-CI

# on:
#   watch:
#     types: started
on:
 push:
   branches:
   - main
   paths-ignore:
     - 'docs/**'
     - 'webullpay-python-sdk-demos/**'
     - 'LICENSE'
     - 'NOTICE'
     - 'README.md'

permissions:
  contents: read

jobs:
  push-webullpay-python-sdk-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip && pip install build
    - name: Build package
      run: python -m build webullpay-python-sdk-core --sdist --wheel --outdir dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  push-webullpay-python-sdk-quotes-core:
    needs: push-webullpay-python-sdk-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip && pip install build
      - name: Build package
        run: python -m build webullpay-python-sdk-quotes-core --sdist --wheel --outdir dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  push-webullpay-python-sdk-mdata:
    needs: push-webullpay-python-sdk-quotes-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip && pip install build
      - name: Build package
        run: python -m build webullpay-python-sdk-mdata --sdist --wheel --outdir dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  push-webullpay-python-sdk-trade-events-core:
    needs: push-webullpay-python-sdk-mdata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip && pip install build
      - name: Build package
        run: python -m build webullpay-python-sdk-trade-events-core --sdist --wheel --outdir dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  push-webullpay-python-sdk-trade:
    needs: push-webullpay-python-sdk-trade-events-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip && pip install build
      - name: Build package
        run: python -m build webullpay-python-sdk-trade --sdist --wheel --outdir dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
